### ISSUE TITLE
Consider adding `/root/.pixi/bin` to the path?

### ISSUE THREAD

**Issue by hmaarrfk** [prefix-dev/pixi-docker#40]
Could be useful when trying to use pixi to create dynamic linting tools.

**Comment by pavelzw** [comment]
I think this makes sense. I don't think there is a way to append to env variables (i.e. `export PATH="/root/.pixi/bin:$PATH"`) in Docker syntax, the only way is to overwrite it using `ENV PATH=...`.
Before doing this, we should make sure we don't accidentally delete parts of the `PATH` of the base images (or add too much).

https://github.com/prefix-dev/pixi-docker/blob/1c419658eae9ce5fc61fceed97538ae43a2d7777/.github/workflows/build.yml#L42-L63

PRs are welcome

**Comment by hadim** [comment]
See https://github.com/prefix-dev/pixi-docker/pull/64
